language: ruby
rvm:
  - 2.1.1
env:
  - DB=sqlite

install:
  - bundle install
before_script:
  - rails g devise user
  - rake db:test:prepare
  - java -jar sunspot_solr_mmseg4j/start.jar &  # start solr server 
script:
  - rspec spec/
