language: ruby
rvm:
  - 2.1.1
env:
  - DB=sqlite

before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
install:
  - bundle install

before_script:
  - rails g devise user
  - rake db:migrate RAILS_ENV=test
  - java -jar sunspot_solr_mmseg4j/start.jar # start solr server 
script:
  - rspec spec/
