language: ruby
rvm:
  - 2.1.1
env:
  - DB=sqlite

before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
  - gem install bundler bundle_cache
install:
  - bundle_cache_install

before_script:
  - rails g devise user
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - java -jar sunspot_solr_mmseg4j/start.jar # start solr server 
script:
  - rspec spec/

after_script:
  - bundle_cache

env:
  global:
  - BUNDLE_ARCHIVE="mei_jing_bundle"
  - AWS_S3_BUCKET="travisci-bundler-cache"
  - RAILS_ENV=test