language: ruby
rvm:
  - 2.1.1
env:
  - DB=sqlite

before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
install:
  - bundle install

before_script:
  # - rails g devise user
  - bundle exec rake db:migrate RAILS_ENV=test
  # - cd sunspot_solr_mmseg4j 
  # - java -jar start.jar & # start solr server
  # - cd .. 
script:
  #- rspec spec/controllers
  - rspec spec/models